### ISSUE TITLE
Hostname is resolved every time in TextLogFileReaderFactory.java 

### ISSUE THREAD

**Issue by v360** [pinterest/singer#44]
As part of 9d123d4, [SingerUtils.getHostNameBasedOnConfig](https://github.com/pinterest/singer/commit/9d123d485fca378a0e8e1b9a35fd255c38351ddf#diff-3b6b1cd36d598c7adc0243da9afc720cR64) is called every time in [TextLogFileReaderFactory.java](https://github.com/pinterest/singer/blob/master/singer/src/main/java/com/pinterest/singer/reader/TextLogFileReaderFactory.java#L64) (irrespective of what prependHostname is configured to).

Running the tutorial on MacOS shows 5 second freezes due to this at times. (there seem to be known issues with InetAddress.getLocalHost().getHostName() on MacOS)  We can avoid this resolution when not configured.

**Comment by ambud** [comment]
Thanks for raising the issue, created a PR to fix.

**Comment by ambud** [comment]
Fix is merged and will be released in Singer 0.8.0.6
